"""Adicionei nova tabela

Revision ID: 648a48933d3d
Revises: 7c458ed4bc49
Create Date: 2025-12-02 07:26:14.869953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648a48933d3d'
down_revision = '7c458ed4bc49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_produto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
